name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ['Continuos Integration']
    types:
      - completed

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverages â¬‡ï¸
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
      - name: Merge coverages ğŸ—ï¸
        run: |
          mkdir -p reports .nyc_output
          cp e2e-coverage/coverage-final.json reports/coverage-e2e.json
          cp unit-coverage/coverage-final.json reports/coverage-unit.json
          npx nyc merge reports
          mv coverage.json .nyc_output/out.json
          npx nyc report --reporter json-summary --report-dir coverage
          npx nyc report --skip-empty --reporter text-summary
      - name: Set code coverage commit status ğŸ“«
        run: npx -p check-code-coverage set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
